### ISSUE TITLE
Weekly Scrum - Week of Feb 28

### ISSUE THREAD

**Issue by yorphos** [Eliasin/sysc4806project#1]

**Comment by yorphos** [comment]
What have I done this week? Nothing yet.
What will I do next week? Configure Heroku (#2) and CircleCI (#3).

**Comment by Eliasin** [comment]
Haven't done anything yet, but will do #8 and #6 and setup example for #9

**Comment by evan-power** [comment]
I haven't done anything yet but will be doing #10

**Comment by CallumCoughlan** [comment]
Did nothing last week but this week I have finished #4 and #5 on the database-basic feature branch. It is ready to merge with the master.
